/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.cf.gui;

import java.awt.Dialog;
import javax.swing.WindowConstants;

/**
 *
 * @author junior
 */
public class TelaInicialGui extends javax.swing.JFrame {

    private CadastrarUsuarioGui cadastrarUsuarioGui;

    public TelaInicialGui() {
        initComponents();
        setLocationRelativeTo(null);
        cadastrarUsuarioGui = new CadastrarUsuarioGui();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        menuTelaInicial = new javax.swing.JMenu();
        menuCadastrar = new javax.swing.JMenu();
        itemCadastrarCategoria = new javax.swing.JMenuItem();
        itemCadastrarConta = new javax.swing.JMenuItem();
        itemCadastrarUsuario = new javax.swing.JMenuItem();
        menuListar = new javax.swing.JMenu();
        itemListarCategoria = new javax.swing.JMenuItem();
        itemListarConta = new javax.swing.JMenuItem();
        itemListarUsuario = new javax.swing.JMenuItem();
        menuAuditar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        menuTelaInicial.setText("Tela inicial");
        menuBar.add(menuTelaInicial);

        menuCadastrar.setText("Cadastrar");

        itemCadastrarCategoria.setText("Categoria");
        menuCadastrar.add(itemCadastrarCategoria);

        itemCadastrarConta.setText("Conta");
        menuCadastrar.add(itemCadastrarConta);

        itemCadastrarUsuario.setText("Usuário");
        itemCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCadastrarUsuarioActionPerformed(evt);
            }
        });
        menuCadastrar.add(itemCadastrarUsuario);

        menuBar.add(menuCadastrar);

        menuListar.setText("Listar");

        itemListarCategoria.setText("Categoria");
        menuListar.add(itemListarCategoria);

        itemListarConta.setText("Conta");
        menuListar.add(itemListarConta);

        itemListarUsuario.setText("Usuário");
        menuListar.add(itemListarUsuario);

        menuBar.add(menuListar);

        menuAuditar.setText("Auditar");
        menuBar.add(menuAuditar);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 389, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadastrarUsuarioActionPerformed
        cadastrarUsuarioGui.setVisible(true);
    }//GEN-LAST:event_itemCadastrarUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemCadastrarCategoria;
    private javax.swing.JMenuItem itemCadastrarConta;
    private javax.swing.JMenuItem itemCadastrarUsuario;
    private javax.swing.JMenuItem itemListarCategoria;
    private javax.swing.JMenuItem itemListarConta;
    private javax.swing.JMenuItem itemListarUsuario;
    private javax.swing.JMenu menuAuditar;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuCadastrar;
    private javax.swing.JMenu menuListar;
    private javax.swing.JMenu menuTelaInicial;
    // End of variables declaration//GEN-END:variables
}
